controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # joint_trajectory_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController
    
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


forward_position_controller:
  ros__parameters:
    joints:
      - prbt_joint_1
      - prbt_joint_2
      - prbt_joint_3
      - prbt_joint_4
      - prbt_joint_5
      - prbt_joint_6
    interface_name: position

# joint_trajectory_controller:
#   ros__parameters:
#     joints:
#       - prbt_joint_1
#       - prbt_joint_2
#       - prbt_joint_3
#       - prbt_joint_4
#       - prbt_joint_5
#       - prbt_joint_6
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity
#     state_publish_rate: 100.0
#     action_monitor_rate: 20.0
#     allow_partial_joints_goal: false
#     constraints:
#       stopped_velocity_tolerance: 0.2
#       goal_time: 0.6
#       stopped_velocity_tolerance: 0.05
#       prbt_joint_1: {trajectory: 0.157, goal: 0.01}
#       prbt_joint_2: {trajectory: 0.157, goal: 0.01}
#       prbt_joint_3: {trajectory: 0.157, goal: 0.01}
#       prbt_joint_4: {trajectory: 0.157, goal: 0.01}
#       prbt_joint_5: {trajectory: 0.157, goal: 0.01}
#       prbt_joint_6: {trajectory: 0.157, goal: 0.01}

arm_controller:
  ros__parameters:
    joints:
      - prbt_joint_1
      - prbt_joint_2
      - prbt_joint_3
      - prbt_joint_4
      - prbt_joint_5
      - prbt_joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    stop_trajectory_duration: 0.2
    state_publish_rate:  100.0
    action_monitor_rate: 50.0
    goal_time: 0.6
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      prbt_joint_1: {trajectory: 0.157, goal: 0.01}
      prbt_joint_2: {trajectory: 0.157, goal: 0.01}
      prbt_joint_3: {trajectory: 0.157, goal: 0.01}
      prbt_joint_4: {trajectory: 0.157, goal: 0.01}
      prbt_joint_5: {trajectory: 0.157, goal: 0.01}
      prbt_joint_6: {trajectory: 0.157, goal: 0.01}
    limits:
      prbt_joint_1:
        has_acceleration_limits: true
        max_acceleration: 6.0
      prbt_joint_2:
        has_acceleration_limits: true
        max_acceleration: 6.0
      prbt_joint_3:
        has_acceleration_limits: true
        max_acceleration: 6.0
      prbt_joint_4:
        has_acceleration_limits: true
        max_acceleration: 6.0
      prbt_joint_5:
        has_acceleration_limits: true
        max_acceleration: 6.0
      prbt_joint_6:
        has_acceleration_limits: true
        max_acceleration: 6.0